name: Deploy Frontend (Windows)

on:
  push:
    branches:
      - main  # deploy when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: windows-latest  # run on Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # root folder containing your HTML/CSS/JS
          publish_branch: gh-pages
